[package]
name = "emailclient"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
log = "0.4"
env_logger = "0.10"
anyhow = "1"
